### ISSUE TITLE
Determine vs examine vs explore

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#11]
https://github.com/asshah4/thesis/blob/66386cde7726107e19fcfd4c3c5ddd9611ef6cd5/dissertation/03-methods.Rmd#L25

I notice you alternate in your aims amongst "determine" "examine" and "explore" - why do you choose one versus the other? I think "examine" is the best
One may argue that we don't have enough sample size to make a determination
I also don't think we're exploratory, given the library of previous work that has preceded this

**Comment by asshah4** [comment]
Agree, believe **examine** is the best option. Will make the change consistent and close.
