### ISSUE TITLE
moderation

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#12]
https://github.com/asshah4/thesis/blob/66386cde7726107e19fcfd4c3c5ddd9611ef6cd5/dissertation/03-methods.Rmd#L30

Looks like you have a sub-hypothesis that depression and PTSD moderate the HRV - MSIMI relationship - not sure where this comes from? I think combining it in this aim makes it harder to read - would recommend removing it

**Comment by asshah4** [comment]
Removed.
