### ISSUE TITLE
purpose of twins

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#17]
https://github.com/asshah4/thesis/blob/5276f86efdcb3a9daf0535e8efab379420fa0be8/dissertation/03-methods.Rmd#L50

The purpose of the initial twins studies was to examine the relationship of depression and PTSD with myocardial perfusion abnormalities, while the most recent ETSF focused on CVD outcomes and changes in perfusion over time. I would describe this first before diving into HRV. Also, since we follow them over time, we would call it a longitudinal cohort study. You can differentiate this from some of your cross-sectional analyses that are nested within the cohort study.

**Comment by asshah4** [comment]
Better this way, changed it to longitudinal
