### ISSUE TITLE
HRV analysis technique

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#19]
https://github.com/asshah4/thesis/blob/66386cde7726107e19fcfd4c3c5ddd9611ef6cd5/dissertation/03-methods.Rmd#L79

I would not call the techniques similar - different ECG acquisition strategies and signal processing methods...the MIMS/MIPS data were analyzed with the GE MARS software, which likely results in different numbers...and of course then there's DYX which was outsourced.

**Comment by asshah4** [comment]
Fair point. I made that change in explanation.
