### ISSUE TITLE
punch line

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#24]
https://github.com/asshah4/thesis/blob/5276f86efdcb3a9daf0535e8efab379420fa0be8/dissertation/05-discussion.Rmd#L3

The first paragraph of the discussion is where you describe the main punch line of the results. Think about how you feel after going to a great lecture, walking out afterwards, and discussing it with your friends...you would say things like "that lecture was exceptional! it helped me to learn X Y and Z...because of what I've learned, I'm going to think about things differently..."

**Comment by asshah4** [comment]
tried to reorganized the main finding paragraph for simplicity
