### ISSUE TITLE
remove?

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#31]
https://github.com/asshah4/thesis/blob/ce02ea311180af7aca04a01b26b374b56ca18a00/thesis/03-methods.Rmd#L213

Can remove since we took out the recurrent events from the outcomes table?

**Comment by asshah4** [comment]
Actually, we kept this in the MIMS/MIPS section for outcomes. I thought it was a nice comparison, with mostly significant findings throughout.
