### ISSUE TITLE
circadian

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#32]
https://github.com/asshah4/thesis/blob/31f4dbdeb443b33321ee3cf2f60c1eca2380b102/thesis/05-discussion.Rmd#L15

Regarding the cosinor findings, see if you can draw parallels to depression and PTSD physiology papers that look at diurnal cortisol variation (depression) and sleep disturbance (PTSD)

**Comment by asshah4** [comment]
https://www.nature.com/articles/s41398-020-0694-0

Great review article on this @ajcshah actually in one of the Nature journals. I read this piece meal and found it helpful.
