### ISSUE TITLE
negative finding

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#34]
https://github.com/asshah4/thesis/blob/31f4dbdeb443b33321ee3cf2f60c1eca2380b102/thesis/05-discussion.Rmd#L53

In the headline, cite your negative biobank finding as well...that there is no association with epicardial disease...adding further emphasis on vasomotor/endothelial/microvascular aspects

**Comment by asshah4** [comment]
Agree. I had hedged on this concept for a bit - if our biobank findings were robust enough to accept the null.
