### ISSUE TITLE
effect size

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#35]
https://github.com/asshah4/thesis/blob/31f4dbdeb443b33321ee3cf2f60c1eca2380b102/thesis/05-discussion.Rmd#L103

The effect size is really impressive and worth commenting upon up front, as this gets at the future relevance of this finding...since you are using standardized units, you could potentially compare it to other biomarkers like LDL cholesterol, CRP, etc, from the literature, where standardized units may also be used. This will probably blow cholesterol out of the water.

**Comment by asshah4** [comment]
You're totally right, HRV is 2-3 times more of hazard than LDL > 200.

https://pubmed.ncbi.nlm.nih.gov/30571575/
