### ISSUE TITLE
contrast with current clinical practice

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#36]
https://github.com/asshah4/thesis/blob/31f4dbdeb443b33321ee3cf2f60c1eca2380b102/thesis/05-discussion.Rmd#L159

Here you can also draw a contrast with current clinical practice which ignores autonomic function and behavioral therapies for the most part...very cost-aversive w/ the current reimbursement models...

**Comment by asshah4** [comment]
Agree!
