### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#5]
https://github.com/asshah4/thesis/blob/db6d3dcd714c1fdecb20638706d59077849595aa/dissertation/03-methods.Rmd#L5

I can appreciate the attempt to give an overview of the aims, but this is not necessary given the exact language you use later on, and the background you presented prior to the aims. I would delete this since it is not customary to include with aims

**Comment by asshah4** [comment]
Easy fix! Good to know.
