### ISSUE TITLE
issue 2

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#6]
https://github.com/asshah4/thesis/blob/db6d3dcd714c1fdecb20638706d59077849595aa/dissertation/03-methods.Rmd#L10

instead of saying "abnormal" consider using relative terms like higher or lower than..."abnormal" suggests that we are using clinical cutpoints.

**Comment by asshah4** [comment]
Updated. That makes sense. Abnormalities require a standardized norm to deviate from, which we don't truly have with these ANS metrics.
