### ISSUE TITLE
Associated with

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#7]
https://github.com/asshah4/thesis/blob/db6d3dcd714c1fdecb20638706d59077849595aa/dissertation/03-methods.Rmd#L12

Use the lingo, "We hypothesize X is associated with Y" rather than "has an increased risk of" - this is safer and does not suggest you are doing a longitudinal study

**Comment by asshah4** [comment]
I changed the aims to use this pattern, instead of "increased risk". I was thinking of using hte word risk as a general term for our measures of *risk* (e.g. odds ratios, hazard ratios, beta estimates, etc). But I think your suggestion is cleaner.
