### ISSUE TITLE
Flavor of ANS dysfunction

### ISSUE THREAD

**Issue by ajcshah** [asshah4/thesis#8]
https://github.com/asshah4/thesis/blob/db6d3dcd714c1fdecb20638706d59077849595aa/dissertation/03-methods.Rmd#L13

Each time you describe autonomic dysfunction in the aim, try to add the "flavor" - for example, "circadian" or "early morning" or "short-term resting" or "mental stress reactivity" etc.

**Comment by asshah4** [comment]
Modified the text to include the autonomic *flavor* as described - I think that's a good idea, as we're using a more nuanced approach.
